
---
- name: Create APPID instance.
  hosts: localhost
  collections:
   - ibm.cloudcollection
  tasks:
  - name: Create a APPID instance
    ibm_resource_instance:
      name: "appid-ansible"
      service: "appid"
      plan: "lite"
      location: "us-south"
